### ISSUE TITLE
DA8 (THS3201D) do podmiany

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM_AFE_PCB_v1.03#1]
Na schemacie THS3201.SchDoc (sekcja C4) jest użyty niepoprawny komponent DA8 (THS3201D) - powinien być: AD8000YRDZ (case: SO8). Taki model stoi na naszej płycie mezzanin z CERN. BTW, THS3201 jest [NOT RECOMMENDED FOR NEW DESIGNS]

![obraz1](https://github.com/alice-fit-fee-upgrade/FIT_PM_AFE_PCB_v1.03/assets/150081866/4a55b112-1728-40a1-8d59-ae65394683fe)

**Comment by gkasprow** [comment]
ACK

**Comment by gkasprow** [comment]
AD8000 ma exposed paddle, ktory winien byc dolaczony do masy
na projekcie nie ma takowego. dorysowac pad czy zostawiamy jak jest?

**Comment by PiotrKazimierzWiacek** [comment]
OK
