### ISSUE TITLE
R8 i R48 do podmiany wartość rezystancji

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM_AFE_PCB_v1.03#2]
Wartości rezystorów R8 i R48 powinny być 360R (case 0805) dla wariantu FV0/FDD.

Rosjanie zmienili wzmocnienie drivera ADC dla det. FV0/FDD na 0.7V/V.
Obecne wartości rez. na schemacie (680R) odpowiadają wariantowi dla FT0 gdzie gain był większy.
![obraz2](https://github.com/alice-fit-fee-upgrade/FIT_PM_AFE_PCB_v1.03/assets/150081866/c98d8f11-2ba1-4204-833b-d372e8a049df)

**Comment by gkasprow** [comment]
ACK
